### ISSUE TITLE
Support mac, linux updater

### ISSUE THREAD

**Issue by Atralupus** [planetarium/9c-launcher#1907]
Survey
- [x] Not working player updater in macOS, maybe permission issue, we should need to survey more
- [x] Not working open player in macOS...
- [ ] Not working launcher updater

Todo
- [x] Fix not found path error in player updater [mac, linux]

prev issue: https://github.com/planetarium/9c-launcher/issues/1900

**Comment by sky1045** [comment]
https://github.com/planetarium/9c-launcher/blob/development/src/main/update/launcher-update.ts#L116

this condition always return true, so macos tries to update forever
because `executePath` will be `/Users/{username}/Library/Application Support/Nine Chonicles/player/main/9c`.
the executable file name should be `9c.app`, not `9c`

**Comment by sky1045** [comment]
https://github.com/planetarium/9c-launcher/blob/development/src/main/main.ts#L369

for macos, node cannot execute `9c.app` directly. i made this work modifying the path to the executable file inside package.(`9c.app/Contents/MacOS/9c`)

i'm not sure why these happen after changing player path, so there would be better solution, but that's all i could solve
