### ISSUE TITLE
V20020 - Launcher closes instead of sending it to tray when pressing X

### ISSUE THREAD

**Issue by FioX0** [planetarium/9c-launcher#2180]
Hi Team,

Not sure if it is a bug or intentional, however with the launcher that's on V20020 when you press X on the UI which previously sent it to system tray, it now closes the whole launcher, which then subsequently takes down the 9C.exe Client with it.

If it was done intentionally, could we considering making an extra option to send it to the tray? From what I could see in the community chat, everyone expects it to go back to the tray.

**Comment by Akamig** [comment]
@FioX0 Ah, we intentionally removed that because of causing problem with restarting launcher completely by update logic, and I found out we don't need to keep launcher opened in background since we don't need to constantly track snapshot or chain tip.

But as you said, it's been a default behavior very long time, and very much agree to provide option for that. I'll work on it soon!

**Comment by FioX0** [comment]
Thanks Akamig,

If closing the launcher wouldn't closing automatically the 9C.exe client automatically it wouldn't be a problem.
As currently to play 9C the launcher needs to be always open and it essentially means you got 2 exact same icons of 2 different apps in your taskbar. While not a major issue, is quite inconvenient when you keep pressing the launcher icon instead of the player icon.

![image](https://github.com/planetarium/9c-launcher/assets/81689614/ba22fa1e-b8dc-4d13-ae41-ba17438c483d)
